# 입양간 기록은 있지만(ANIMAL_OUTS), 보호소에 들어온 기록이 없는(ANIMAL_INS) 
# 동물의 ID, 이름을 ID순으로 조회


# SELECT OUTS.ANIMAL_ID, OUTS.NAME
# FROM ANIMAL_OUTS OUTS
# LEFT OUTER JOIN ANIMAL_INS INS
# ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
# WHERE INS.ANIMAL_ID is NULL
# ORDER BY OUTS.ANIMAL_ID

select B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS AS A right outer join ANIMAL_OUTS AS B
ON A.ANIMAL_ID	 = B.ANIMAL_ID
WHERE A.ANIMAL_ID is null
ORDER BY B.ANIMAL_ID asc;