-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY in ('과자', '국', '김치', '식용유') 
    AND
    (CATEGORY, PRICE) in (
        SELECT CATEGORY, MAX(PRICE)
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY
    )
ORDER BY PRICE DESC;